name: DimensionControl
version: '1.0.3'
main: de.jakomi1.dimensionControl.DimensionControl
api-version: '1.21'
folia-supported: false
commands:
  dimension:
    usage: /dimension
    aliases: [dim]
permissions:
  dimensioncontrol.dimension.add:
    default: op
  dimensioncontrol.dimension.remove:
    default: op
  dimensioncontrol.dimension.reset:
    default: op
  dimensioncontrol.dimension.teleport:
    default: op
  dimensioncontrol.dimension.list:
    default: op
  dimensioncontrol.dimension.*:
    default: op